SENDGRID_USERNAME:
SENDGRID_PASSWORD:

FB_APP_ID:              
FB_APP_SECRET:          
TT_APP_ID:
TT_APP_SECRET:
WECHAT_APP_ID:
WECHAT_APP_SECRET:

AWS_ACCESS_KEY_ID:      
AWS_SECRET_ACCESS_KEY:  

development:
  S3_BUCKET_NAME:       
production:
  S3_BUCKET_NAME:       
  ADMIN_NAME:
  ADMIN_EMAIL:
  ADMIN_PASSWORD:
  DOMAIN_NAME: